# live one
spring.datasource.url=jdbc:postgresql://dpg-d6lhkkfkijhs739ad780-a:5432/taskflow_db_fr0d
spring.datasource.username=taskflow_db_fr0d_user
spring.datasource.password=oy9qyC210c0LQHn4yTI0G2qiC4yYAOe6
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=10000
spring.application.name=taskflow-api

# spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_db
# spring.datasource.username=postgres
# spring.datasource.password=postgress
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# server.port=8080
# spring.application.name=taskflow-api
